language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

# Add test requirements; travis will do the rest
before_install:
  - cat requirements-test.txt >> requirements.txt

# command to run tests
script:
  - python setup.py install
  - python -c 'import sys; print(sys.path)'
  - python -c 'import coverage'
  - python -m nose --with-coverage --cover-package=wstool test/local

  # Install rosinstall from pip and perform a sanity check
  - pip install --upgrade rosinstall
  - rosws
notifications:
  email: false
after_success:
  - coveralls
